heat_template_version: rocky

# NOTE: You don't need to pass the parameter explicitly from the
# parent template, it can be specified via the parameter_defaults
# in the resource_registry instead, if you want to override the default
# and/or share values with other templates in the tree.
parameters:
  RoleParameters:
    type: json
    description: Role Specific parameters
    default: {}
  ServiceNames:
    type: comma_delimited_list
    default: []
  deployment_actions:
    default: ['CREATE']
    type: comma_delimited_list
    description: >
      List of stack actions that will trigger any deployments in this
      templates. The actions will be an empty list of the server is in the
      toplevel DeploymentServerBlacklist parameter's value.
  server:
    type: string
  ContrailVrouterModuleOptions:
    default: ''
    description: >
      Vrouter kernel module options.
      This string is passed to agent container as env variable VROUTER_MODULE_OPTIONS
      (by a chance if vrouter module is loaded by container) and
      it is saved as options in /etc/modprobe.d/vrouter.conf for a case
      when vrouter is loaded by ifup scripts called by os-collect-config from host.
      E.g. vr_mpls_labels=196000 vr_nexthops=521000 vr_vrfs=65536 vr_bridge_entries=1000000
    type: string
  ContrailSriovNumVFs:
    description: >
      Provide the list of VFs to be reserved for each SR-IOV interface.
      Format "<interface_name1>:<numvfs1>,<interface_name2>:<numvfs2>"
      Example "eth1:4096,eth2:128"
    type: comma_delimited_list
    default: ""
  ContrailDpdkOptions:
    default: ''
    description: >
      Vrouter dpdk advanced options.
      This string is passed to dpdk container as env variable DPDK_COMMAND_ADDITIONAL_ARGS,
      so dpdk command line is populated with arguments from this string.
      E.g. --vr_mempool_sz --dpdk_txd_sz --dpdk_rxd_sz
      dpdk --vr_dpdk_rx_ring_sz <int>  --vr_dpdk_tx_ring_sz <int> –-yield_option ‘0 or 1’
    type: string
  ContrailSriovMode:
    default: 'kernel'
    type: string
    tags:
      - role_specific
  DockerInsecureRegistryAddress:
    description: Optional. The IP Address and Port of an insecure docker
                 namespace that will be configured in /etc/sysconfig/docker.
                 The value can be multiple addresses separated by commas.
    type: comma_delimited_list
    default: []
  ContrailRegistry:
    default: 'opencontrailnightly'
    description: Contrail Registry
    type: string
  ContrailImageTag:
    default: 'latest'
    description: Contrail container image tag
    type: string
  DockerContrailVrouterKernelInitImageName:
    description: image
    type: string
    default: "contrail-vrouter-kernel-init"
  DockerContrailVrouterKernelInitDpdkImageName:
    description: image
    type: string
    default: "contrail-vrouter-kernel-init-dpdk"
  DockerContrailVrouterAgentDpdkContainerName:
    description: image
    type: string
    default: "contrail-vrouter-agent-dpdk"
  DockerContrailVrouterAgentContainerName:
    description: image
    type: string
    default: "contrail-vrouter-agent"
  DockerContrailVrouterPluginInitImageName:
    description: >
      Vrouter plugin init container image name.
      It is a name of the vrouter plugin init image. It is
      for cases when third-party HW requires specific drivers to be installed.
      E.g. Mellanox requries some drivers on host to be installed.
      For Mellanox the image name is contrail-vrouter-plugin-mellanox-init-redhat
    type: string
    default: ''
  NodeDataLookup:
    type: json
    default: {}
    description: json string containing per-node configuration map
  ContrailSettings:
    default: {}
    description: Contrail Service settings
    type: json

description: >
  This template installs the Contrail dpdk packages in order
  to bring vhost0 interface up. Vhost0 interface must be up before
  os-net-config takes over.

conditions:
  deployment_actions_empty:
    equals:
      - {get_param: deployment_actions}
      - []
  is_dpdk: {equals: [{get_param: [RoleParameters, ContrailSriovMode]}, 'dpdk']}

resources:
  DockerContrailVrouterKernelImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterKernelInitImageName}

  DockerContrailVrouterKernelInitDpdkImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterKernelInitDpdkImageName}

  DockerContrailVrouterAgentDpdkImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterAgentDpdkContainerName}

  DockerContrailVrouterAgentImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterAgentContainerName}

  DockerContrailVrouterPluginInitImageNormalize:
    type: ../../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterPluginInitImageName}

  ContrailSettingsRoleParametersValue:
    type: OS::Heat::Value
    properties:
      type: json
      value:
        map_merge:
          - contrail_settings:
              yaql:
                expression: $.data.default.mergeWith($.data.overrides != null and $.data.overrides or dict())
                data:
                  default: {get_param: ContrailSettings}
                  overrides: {get_param: [RoleParameters, ContrailSettings]}
          - map_replace:
            - map_replace:
              - sriov_num: ContrailSriovNumVFs
                vrouter_module_opts: ContrailVrouterModuleOptions
                dpdk_options: ContrailDpdkOptions
              - values: {get_param: [RoleParameters]}
            - values:
                ContrailSriovNumVFs: {get_param: ContrailSriovNumVFs}
                ContrailVrouterModuleOptions: {get_param: ContrailVrouterModuleOptions}
                ContrailDpdkOptions: {get_param: ContrailDpdkOptions}

  SriovHostParametersConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: _CONTRAIL_SRIOV_NUM_VFS_
        - name: _IS_DPDK_
      outputs:
        - name: result
      config:
        get_file: contrail_ansible_host_config.yaml

  SriovHostParametersDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: SriovHostParametersDeployment
      server:  {get_param: server}
      config: {get_resource: SriovHostParametersConfig}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE', 'UPDATE']
      input_values:
        _CONTRAIL_SRIOV_NUM_VFS_: {get_attr: [ContrailSettingsRoleParametersValue, value, sriov_num]}
        _IS_DPDK_: {if: [is_dpdk, 'True', '']}

  SriovContainerParametersConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ansible
      inputs:
        - name: _NODEDATA_
          type: Json
        - name: _CONTRAIL_SETTINGS_
          type: Json
        - name: _CONTRAIL_VROUTER_INIT_IMAGE_
        - name: _CONTRAIL_VROUTER_INIT_IMAGE_NAME_
        - name: _CONTRAIL_VROUTER_AGENT_DPDK_IMAGE_
        - name: _CONTRAIL_VROUTER_AGENT_DPDK_CONTAINER_NAME_
        - name: _CONTRAIL_VROUTER_MODULE_OPTS_
        - name: _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_
        - name: _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_NAME_
        - name: _CONTRAIL_DPDK_COMMAND_ADDITIONAL_ARGS_
        - name: _DOCKER_INSECURE_REGISTRIES_
        - name: _IS_DPDK_
      outputs:
        - name: result
      config:
        get_file: contrail_ansible_container_config.yaml

  SriovContainerParametersDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      name: SriovContainerParametersDeployment
      server:  {get_param: server}
      config: {get_resource: SriovContainerParametersConfig}
      actions:
        if:
          - deployment_actions_empty
          - []
          - ['CREATE', 'UPDATE']
      input_values:
        _NODEDATA_: {get_param: NodeDataLookup}
        _CONTRAIL_SETTINGS_: {get_attr: [ContrailSettingsRoleParametersValue, value, contrail_settings]}
        _CONTRAIL_VROUTER_INIT_IMAGE_: {if: [is_dpdk, {get_attr: [DockerContrailVrouterKernelInitDpdkImageNormalize, contrail_image]}, {get_attr: [DockerContrailVrouterKernelImageNormalize, contrail_image]}]}
        _CONTRAIL_VROUTER_INIT_IMAGE_NAME_: {if: [is_dpdk, {get_attr: [DockerContrailVrouterKernelInitDpdkImageNormalize, contrail_image_only]}, {get_attr: [DockerContrailVrouterKernelImageNormalize, contrail_image_only]}]}
        _CONTRAIL_VROUTER_AGENT_DPDK_IMAGE_: {get_attr: [DockerContrailVrouterAgentDpdkImageNormalize, contrail_image]}
        _CONTRAIL_VROUTER_AGENT_DPDK_CONTAINER_NAME_: {get_attr: [DockerContrailVrouterAgentDpdkImageNormalize, contrail_image_only]}
        _CONTRAIL_VROUTER_MODULE_OPTS_: {get_attr: [ContrailSettingsRoleParametersValue, value, vrouter_module_opts]}
        _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_: {get_attr: [DockerContrailVrouterPluginInitImageNormalize, contrail_image]}
        _CONTRAIL_VROUTER_PLUGIN_INIT_IMAGE_NAME_: {get_attr: [DockerContrailVrouterPluginInitImageNormalize, contrail_image_only]}
        _CONTRAIL_DPDK_COMMAND_ADDITIONAL_ARGS_: {get_attr: [ContrailSettingsRoleParametersValue, value, dpdk_options]}
        _DOCKER_INSECURE_REGISTRIES_: {get_param: DockerInsecureRegistryAddress}
        _IS_DPDK_: {if: [is_dpdk, 'True', '']}
    depends_on:
      - SriovHostParametersDeployment
      - DockerContrailVrouterPluginInitImageNormalize
      - DockerContrailVrouterKernelImageNormalize
      - DockerContrailVrouterAgentImageNormalize
      - DockerContrailVrouterAgentDpdkImageNormalize
      - DockerContrailVrouterKernelInitDpdkImageNormalize


outputs:
  result:
    value:
      get_attr: [SriovContainerParametersDeployment, result]
  stdout:
    value:
      get_attr: [SriovContainerParametersDeployment, deploy_stdout]
  stderr:
    value:
      get_attr: [SriovContainerParametersDeployment, deploy_stderr]
  status_code:
    value:
      get_attr: [SriovContainerParametersDeployment, deploy_status_code]
