heat_template_version: rocky

description: >
  Contrail containerized Vrouter service

parameters:
  DockerContrailVrouterKernelInitImageName:
    description: image
    type: string
    default: "contrail-vrouter-kernel-init"
  DockerContrailVrouterAgentImageName:
    description: image
    type: string
    default: "contrail-vrouter-agent"
  ContrailImageTag:
      default: 'latest'
      description: Contrail container image tag
      type: string
  DockerContrailNovaPluginImageName:
    description: image
    type: string
    default: "contrail-openstack-compute-init"
  NeutronMetadataProxySharedSecret:
    description: Metadata Secret
    type: string
    hidden: true
  ContrailVrouterModuleOptions:
    default: ''
    description: >
      Vrouter kernel module options.
      This string is passed to agent container as env variable VROUTER_MODULE_OPTIONS
      (by a chance if vrouter module is loaded by container) and
      it is saved as options in /etc/modprobe.d/vrouter.conf for a case
      when vrouter is loaded by ifup scripts called by os-collect-config from host.
      E.g. vr_mpls_labels=196000 vr_nexthops=521000 vr_vrfs=65536 vr_bridge_entries=1000000
    type: string
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json

conditions:
  is_more_than_2001_or_latest:
    or:
      - yaql:
          expression: $.data.matches(".*dev.*")
          data: {get_param: ContrailImageTag}
      - yaql:
          expression: $.data.matches(".*latest.*")
          data: {get_param: ContrailImageTag}
      - yaql:
          expression: $.data.matches(".*master.*")
          data: {get_param: ContrailImageTag}
      - and:
        - not:
            yaql:
              expression: $.data.split(".").select($.split("-")).flatten().where($.matches("^[0-9]{4,}$")).where(int($) < 2001).any()
              data: {get_param: ContrailImageTag}
        - not:
            yaql:
              expression: $.data.split(".").select($.split("-")).flatten().where($.matches("^r[0-9]{4}$")).where(int($.substring(-4)) < 2001).any()
              data: {get_param: ContrailImageTag}

resources:
  DockerContrailVrouterKernelImageNormalize:
    type: ../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterKernelInitImageName}
  DockerContrailVrouterAgentImageNormalize:
    type: ../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailVrouterAgentImageName}

  DockerContrailNovaPluginImageNormalize:
    type: ../../tools/contrail/contrail-image-normalize.yaml
    properties:
      GenericImageName: {get_param: DockerContrailNovaPluginImageName}

  ContrailBase:
    type: contrail-base.yaml
    properties:
      EndpointMap: {get_param: EndpointMap}
      ServiceData: {get_param: ServiceData}
      ServiceNetMap: {get_param: ServiceNetMap}
      DefaultPasswords: {get_param: DefaultPasswords}
      RoleName: {get_param: RoleName}
      RoleParameters: {get_param: RoleParameters}
      contrail_env_name: 'vrouter'

  ContrailVrouterBase:
    type: contrail-vrouter-base.yaml

outputs:
  role_data:
    description: Role data for the Contrail Vrouter service.
    value:
      service_name: contrail_vrouter
      config_settings:
        map_merge:
          - get_attr: [ContrailBase, role_data, config_settings]
          - contrail::vrouter::metadata_proxy_shared_secret: {get_param: NeutronMetadataProxySharedSecret}
            tripleo.contrail_vrouter.firewall_rules:
              '111 contrail_vrouter_8085_8097':
                dport:
                  - 8085
                  - 8097
                  - 8102
                  - 9091
      contrail_env_file: &contrail_env_file
        get_attr: [ContrailVrouterBase, role_data, contrail_env_file]
      vrouter_init_container_name: &vrouter_init_container_name
        {get_attr: [DockerContrailVrouterKernelImageNormalize, contrail_image_only]}
      docker_config:
        step_3:
          contrail_nova_plugin:
            image: &contrail_nova_plugin_image {get_attr: [DockerContrailNovaPluginImageNormalize, contrail_image]}
            net: none
            volumes:
              - /var/lib/contrail/vrouter_port_control:/opt/plugin/bin:z
              - /var/lib/contrail/vif_nova_contrail:/opt/plugin/site-packages/nova_contrail_vif:z
              - /var/lib/contrail/vif_nova_contrail_egg:/opt/plugin/site-packages/nova_contrail_vif-0.1-py2.7.egg-info:z
              - /var/lib/contrail/vif_plug_vrouter:/opt/plugin/site-packages/vif_plug_vrouter:z
              - /var/lib/contrail/vif_plug_contrail_vrouter:/opt/plugin/site-packages/vif_plug_contrail_vrouter:z
            environment:
              get_attr: [ContrailBase, role_data, contrail_base_env]
            env_file:
              list_concat:
                - {get_attr: [ContrailBase, role_data, contrail_base_env_file]}
                - - *contrail_env_file
        step_5:
          map_merge:
            - if:
                - is_more_than_2001_or_latest
                - contrail_vrouter_agent_provisioner:
                    image: {get_attr: [ContrailBase, role_data, contrail_provisioner_image_name]}
                    net: host
                    detach: true
                    user: root
                    restart: on-failure
                    volumes:
                      get_attr: [ContrailBase, role_data, contrail_base_volumes]
                    environment:
                      map_merge:
                        - {get_attr: [ContrailBase, role_data, contrail_base_env]}
                        - {get_attr: [ContrailBase, role_data, contrail_defaults_env]}
                    env_file:
                      list_concat:
                        - {get_attr: [ContrailBase, role_data, contrail_base_env_file]}
                        - - *contrail_env_file
                - null
            - contrail_vrouter_agent_nodemgr:
                image: {get_attr: [ContrailBase, role_data, contrail_nodemgr_image_name]}
                net: host
                detach: true
                user: root
                privileged: true
                restart: always
                volumes:
                  list_concat:
                    - {get_attr: [ContrailBase, role_data, contrail_base_volumes]}
                    - - /var/run:/var/run:z
                    - - /var/lib/contrail/loadbalancer:/var/lib/contrail/loadbalancer
                environment:
                  get_attr: [ContrailBase, role_data, contrail_base_env]
                env_file:
                  list_concat:
                    - {get_attr: [ContrailBase, role_data, contrail_base_env_file]}
                    - - *contrail_env_file
              contrail_vrouter_agent:
                image: &contrail_vrouter_agent_image {get_attr: [DockerContrailVrouterAgentImageNormalize, contrail_image]}
                net: host
                privileged: true
                detach: true
                user: root
                restart: always
                volumes:
                  list_concat:
                    - {get_attr: [ContrailBase, role_data, contrail_base_volumes]}
                    - - /dev:/dev
                      - /etc/sysconfig/network-scripts:/etc/sysconfig/network-scripts:z
                      - /lib/modules:/lib/modules:z
                      - /var/run:/var/run:z
                      - /var/lib/contrail:/var/lib/contrail:z
                environment:
                  map_merge:
                    - {get_attr: [ContrailBase, role_data, contrail_base_env]}
                    - VROUTER_MODULE_OPTIONS: {get_param: ContrailVrouterModuleOptions}
                      KERNEL_INIT_VHOST0: 'false'
                env_file:
                  list_concat:
                    - {get_attr: [ContrailBase, role_data, contrail_base_env_file]}
                    - - *contrail_env_file
      host_prep_tasks:
        list_concat:
          - {get_attr: [ContrailBase, role_data, contrail_host_prep_tasks_base]}
          - {get_attr: [ContrailVrouterBase, role_data, host_prep_tasks]}
          - {get_attr: [ContrailBase, role_data, contrail_config_volume_prep]}

      metadata_settings:
        get_attr: [ContrailBase, role_data, metadata_settings]

      update_tasks:
        get_attr: [ContrailVrouterBase, role_data, update_tasks]

      reinit_vhost_tasks: &reinit_vhost_tasks
        - name: Set contrail-vrouter-kernel-init container name
          set_fact:
            vrouter_init_container_name_ansible: *vrouter_init_container_name
        - name: Start contrail-vrouter-kernel-init container as post update
          shell: >
            {{ container_cli }} start -i {{ vrouter_init_container_name_ansible }}
        - name: Restart vhost0 interface
          shell: |
            ifdown vhost0
            ifup vhost0
            {{ container_cli }} start -i contrail_vrouter_agent
          ignore_errors: yes

      post_update_tasks:
        list_concat:
          - {get_attr: [ContrailVrouterBase, role_data, post_update_tasks]}
          - *reinit_vhost_tasks

      fast_forward_upgrade_tasks:
        get_attr: [ContrailVrouterBase, role_data, fast_forward_upgrade_tasks]

      fast_forward_post_upgrade_tasks:
        get_attr: [ContrailVrouterBase, role_data, fast_forward_post_upgrade_tasks]

      upgrade_tasks:
        list_concat:
          - {get_attr: [ContrailBase, role_data, upgrade_tasks_common]}
          - {get_attr: [ContrailVrouterBase, role_data, upgrade_tasks]}
          - - name: run init container to put vrouter ko for newer kernel
              tags:
                - never
                - system_upgrade
                - system_upgrade_prepare
              when:
                - step|int == 1
                - upgrade_leapp_enabled
              block:
                - name: HACK create /lib/modules/4.18.0-193.6.3.el8_2.x86_64/kernel/net/
                  file:
                    path: "/lib/modules/4.18.0-193.6.3.el8_2.x86_64/kernel/net/"
                    state: directory
                    recurse: yes
                - name: Set contrail-vrouter-kernel-init container name
                  set_fact:
                    vrouter_init_container_name_ansible: *vrouter_init_container_name
                - name: Start contrail-vrouter-kernel-init container for system_upgrade
                  shell: |
                    set -eux
                    if type docker &> /dev/null ; then
                        docker start -i {{ vrouter_init_container_name_ansible }}
                    else
                        podman start -i {{ vrouter_init_container_name_ansible }}
                    fi
                  ignore_errors: yes

      post_upgrade_tasks:
        list_concat:
          - {get_attr: [ContrailVrouterBase, role_data, post_upgrade_tasks]}
          - *reinit_vhost_tasks
